### ISSUE TITLE
Where can I find the `split_test.txt`

### ISSUE THREAD

**Issue by moqingyan** [MengyuanChen21/CVPR2022-FTCL#4]
After I downloaded and setting up the directory as instructed, I received an error by running the test:
```
python main_thu.py --test --checkpoint <home>/CVPR2022-FTCL/data/model/THUMOS-14/THUMOS_best.pth
Namespace(seed=0, model_name='default', group='default', checkpoint='<home>/CVPR2022-FTCL/data/model/THUMOS-14/THUMOS_best.pth', start_epoch=0, gpu='0', num_workers=0, dataset='THUMOS', batch_size=16, epochs=25, start_test_epoch=0, loss_lamb_lcs=0.1, loss_lamb_fsd=0.8, thres=0.92, lcs_len=30, fsd_len=5, fc_dim=1024, without_wandb=False, test=True, ftcl=False, without_lcs=False, without_fsd=False, class_name_lst=['BaseballPitch', 'BasketballDunk', 'Billiards', 'CleanAndJerk', 'CliffDiving', 'CricketBowling', 'CricketShot', 'Diving', 'FrisbeeCatch', 'GolfSwing', 'HammerThrow', 'HighJump', 'JavelinThrow', 'LongJump', 'PoleVault', 'Shotput', 'SoccerPenalty', 'TennisSwing', 'ThrowDiscus', 'VolleyballSpiking'], action_cls_num=20, dropout=0.7, lr=0.0001, weight_decay=5e-05, frames_per_sec=25, segment_frames_num=16, sample_segments_num=750, feature_dim=2048, cls_threshold=0.25, tiou_thresholds=array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]), test_gt_file_path='<home>/CVPR2022-FTCL/data/THUMOS-14/gt.json', data_dir='<home>/CVPR2022-FTCL/data/THUMOS-14', test_upgrade_scale=20, nms_thresh=0.55, ins_topk_seg=8, con_topk_seg=3, bak_topk_seg=3, loss_lamb_1=0.002, loss_lamb_2=5e-05, loss_lamb_3=0.0002)
Traceback (most recent call last):
  File "<home>/CVPR2022-FTCL/main_thu.py", line 146, in <module>
    main(args)
  File "<home>/CVPR2022-FTCL/main_thu.py", line 129, in main
    test_dataset = build_dataset(args, phase="test", sample="uniform")
  File "<home>/CVPR2022-FTCL/dataset/dataset_class.py", line 125, in build_dataset
    return ACMDataset(args, phase, sample)
  File "<home>/CVPR2022-FTCL/dataset/dataset_class.py", line 74, in __init__
    self.data_list = list(open(os.path.join(self.data_dir, "split_test.txt")))
FileNotFoundError: [Errno 2] No such file or directory: '<home>/CVPR2022-FTCL/data/THUMOS-14/split_test.txt'
```
It seems the file `split_test.txt` is missing, but I failed to find it in the provided google drive link or the THUMOS website. Can you help me out? 

Thank you in advance!

**Comment by MengyuanChen21** [comment]
Thanks for reaching out! 

The file can be found in the repo of our baseline method [ACM-Net](https://github.com/ispc-lab/ACM-Net). Besides, I have also uploaded the related files to `/data/THUMOS14` just now.

**Comment by moqingyan** [comment]
Thank you! I can find the file now. :)
